import type { Client, Invoice, DashboardData, InvoiceStatus } from "./types";

export const mockClients: Client[] = [
  // This will be replaced by Firestore data.
  { id: '1', userId: 'user-1', name: 'Acme Inc.', email: 'contact@acme.com', avatarUrl: 'https://placehold.co/40x40', createdAt: new Date() },
  { id: '2', userId: 'user-1', name: 'Stark Industries', email: 'tony@starkindustries.com', avatarUrl: 'https://placehold.co/40x40', createdAt: new Date() },
  { id: '3', userId: 'user-1', name: 'Wayne Enterprises', email: 'bruce@wayne.com', avatarUrl: 'https://placehold.co/40x40', createdAt: new Date() },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-001',
    userId: 'user-1',
    clientId: '1',
    invoiceNumber: 'INV-2024-001',
    client: mockClients[0],
    items: [{ id: 'item-1', description: 'Web Development Services', quantity: 1, price: 2500 }],
    taxes: [],
    subtotal: 2500,
    total: 2750,
    status: 'Paid' as InvoiceStatus,
    issueDate: new Date('2024-06-01'),
    dueDate: new Date('2024-06-15'),
    createdAt: new Date('2024-06-01'),
    notes: 'Thank you for your business.',
  },
  {
    id: 'inv-002',
    userId: 'user-1',
    clientId: '2',
    invoiceNumber: 'INV-2024-002',
    client: mockClients[1],
    items: [{ id: 'item-1', description: 'Arc Reactor Maintenance', quantity: 1, price: 10000 }],
    taxes: [],
    subtotal: 10000,
    total: 11000,
    status: 'Pending' as InvoiceStatus,
    issueDate: new Date('2024-07-10'),
    dueDate: new Date('2024-07-25'),
    createdAt: new Date('2024-07-10'),
    notes: 'Net 15 terms.',
  },
  {
    id: 'inv-003',
    userId: 'user-1',
    clientId: '3',
    invoiceNumber: 'INV-2024-003',
    client: mockClients[2],
    items: [{ id: 'item-1', description: 'Security Consulting', quantity: 10, price: 500 }],
    taxes: [],
    subtotal: 5000,
    total: 5500,
    status: 'Overdue' as InvoiceStatus,
    issueDate: new Date('2024-05-20'),
    dueDate: new Date('2024-06-05'),
    createdAt: new Date('2024-05-20'),
    notes: 'Please remit payment promptly.',
  },
  {
    id: 'inv-004',
    userId: 'user-1',
    clientId: '4',
    invoiceNumber: 'INV-2024-004',
    client: { id: '4', userId: 'user-1', name: 'Ollivanders Wand Shop', email: 'sales@ollivanders.co.uk', avatarUrl: 'https://placehold.co/40x40', createdAt: new Date() },
    items: [{ id: 'item-1', description: 'Phoenix Feather Wand', quantity: 1, price: 700 }],
    taxes: [],
    subtotal: 700,
    total: 770,
    status: 'Paid' as InvoiceStatus,
    issueDate: new Date('2024-07-01'),
    dueDate: new Date('2024-07-15'),
    createdAt: new Date('2024-07-01'),
    notes: '',
  },
  {
    id: 'inv-005',
    userId: 'user-1',
    clientId: '1',
    invoiceNumber: 'INV-2024-005',
    client: mockClients[0],
    items: [{ id: 'item-1', description: 'Monthly Retainer - Marketing', quantity: 1, price: 1500 }],
    taxes: [],
    subtotal: 1500,
    total: 1650,
    status: 'Pending' as InvoiceStatus,
    issueDate: new Date('2024-07-05'),
    dueDate: new Date('2024-08-01'),
    createdAt: new Date('2024-07-05'),
    notes: '',
  },
    {
    id: 'inv-006',
    userId: 'user-1',
    clientId: '5',
    invoiceNumber: 'INV-2024-006',
    client: { id: '5', userId: 'user-1', name: 'Gekko & Co.', email: 'gordon@gekko.com', avatarUrl: 'https://placehold.co/40x40', createdAt: new Date() },
    items: [{ id: 'item-1', description: 'Financial Advisory', quantity: 1, price: 5000 }],
    taxes: [],
    subtotal: 5000,
    total: 5500,
    status: 'Pending' as InvoiceStatus,
    issueDate: new Date('2024-07-15'),
    dueDate: new Date('2024-07-30'),
    createdAt: new Date('2024-07-15'),
    notes: 'Greed is good.',
  },
];


export const mockDashboardData: DashboardData = {
    totalRevenue: 25000,
    revenueChange: "+15.2% from last month",
    paidInvoices: 12,
    pendingInvoices: 5,
    overdueInvoices: 2,
}
