import type { Client, Invoice, DashboardData, InvoiceStatus } from "./types";

export const mockClients: Client[] = [
  // This will be replaced by Firestore data.
  { id: '1', name: 'Acme Inc.', email: 'contact@acme.com', avatarUrl: 'https://placehold.co/40x40' },
  { id: '2', name: 'Stark Industries', email: 'tony@starkindustries.com', avatarUrl: 'https://placehold.co/40x40' },
  { id: '3', name: 'Wayne Enterprises', email: 'bruce@wayne.com', avatarUrl: 'https://placehold.co/40x40' },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'INV-2024-001',
    client: { id: '1', name: 'Acme Inc.', email: 'contact@acme.com', avatarUrl: 'https://placehold.co/40x40' },
    items: [{ id: 'item-1', description: 'Web Development Services', quantity: 1, price: 2500 }],
    subtotal: 2500,
    tax: 250,
    total: 2750,
    status: 'Paid',
    issueDate: '2024-06-01',
    dueDate: '2024-06-15',
    notes: 'Thank you for your business.',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'INV-2024-002',
    client: { id: '2', name: 'Stark Industries', email: 'tony@starkindustries.com', avatarUrl: 'https://placehold.co/40x40' },
    items: [{ id: 'item-1', description: 'Arc Reactor Maintenance', quantity: 1, price: 10000 }],
    subtotal: 10000,
    tax: 1000,
    total: 11000,
    status: 'Pending',
    issueDate: '2024-07-10',
    dueDate: '2024-07-25',
    notes: 'Net 15 terms.',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'INV-2024-003',
    client: { id: '3', name: 'Wayne Enterprises', email: 'bruce@wayne.com', avatarUrl: 'https://placehold.co/40x40' },
    items: [{ id: 'item-1', description: 'Security Consulting', quantity: 10, price: 500 }],
    subtotal: 5000,
    tax: 500,
    total: 5500,
    status: 'Overdue',
    issueDate: '2024-05-20',
    dueDate: '2024-06-05',
    notes: 'Please remit payment promptly.',
  },
  {
    id: 'inv-004',
    invoiceNumber: 'INV-2024-004',
    client: { id: '4', name: 'Ollivanders Wand Shop', email: 'sales@ollivanders.co.uk', avatarUrl: 'https://placehold.co/40x40' },
    items: [{ id: 'item-1', description: 'Phoenix Feather Wand', quantity: 1, price: 700 }],
    subtotal: 700,
    tax: 70,
    total: 770,
    status: 'Paid',
    issueDate: '2024-07-01',
    dueDate: '2024-07-15',
    notes: '',
  },
  {
    id: 'inv-005',
    invoiceNumber: 'INV-2024-005',
    client: { id: '1', name: 'Acme Inc.', email: 'contact@acme.com', avatarUrl: 'https://placehold.co/40x40' },
    items: [{ id: 'item-1', description: 'Monthly Retainer - Marketing', quantity: 1, price: 1500 }],
    subtotal: 1500,
    tax: 150,
    total: 1650,
    status: 'Pending',
    issueDate: '2024-07-05',
    dueDate: '2024-08-01',
    notes: '',
  },
    {
    id: 'inv-006',
    invoiceNumber: 'INV-2024-006',
    client: { id: '5', name: 'Gekko & Co.', email: 'gordon@gekko.com', avatarUrl: 'https://placehold.co/40x40' },
    items: [{ id: 'item-1', description: 'Financial Advisory', quantity: 1, price: 5000 }],
    subtotal: 5000,
    tax: 500,
    total: 5500,
    status: 'Pending',
    issueDate: '2024-07-15',
    dueDate: '2024-07-30',
    notes: 'Greed is good.',
  },
];


export const mockDashboardData: DashboardData = {
    totalRevenue: 25000,
    revenueChange: "+15.2% from last month",
    paidInvoices: 12,
    pendingInvoices: 5,
    overdueInvoices: 2,
}
